"""empty message

Revision ID: 7960a3dfb598
Revises: 4ba75e083ac5
Create Date: 2025-06-15 15:17:45.275845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7960a3dfb598'
down_revision: Union[str, None] = '4ba75e083ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'modify_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('question', 'modify_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'modify_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('answer', 'modify_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
